== Requirements Classes for Style Encodings

[[rc_sld-se]]
=== Requirements Class "OGC Styled Layer Descriptor / Symbology Encoding"

include::requirements/requirements_class_sld-se.adoc[]

[[req_sld-se_media-type]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sld-se/media-type*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL support the media type `application/vnd.ogc.sld+xml`.
^|B |The server SHALL accept either version 1.0 or 1.1 of SLD/SE (or both), specified with media type parameter `;version=1.0` or `;version=1.1`.
|===

[[req_sld-se_valid]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sld-se/valid*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL accept valid OGC SLD/SE documents without errors for the supported version(s).
|===

The list of operations in a server implementing all conformance classes of this draft specification is:

* POST `{baseResource}/styles`
* PUT `{baseResource}/styles/{styleId}`

[[sld-se_content]]
==== Expected content in an SLD/SE document

[[req_sld-se_root]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sld-se/root*
^|A |In accordance with the SLD/SE standard, the server SHALL accept SLD/SE stylesheets whose root element is a `StyledLayerDescriptor` element.
|===

The styling rules inside stylesheet document will typically reference individual feature types and coverages, which potentially may also be available as OGC API collections
at a `{baseResource}/collections` endpoint:

[[req_sld-se_content]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sld-se/content*
^|A |The document SHALL contain one or more `NamedLayer` or `UserLayer` elements, each with at least one `UserStyle`.
^|B a|The specific feature type or coverage being styled SHALL be declared using either:

- for features, with SLD/SE 1.1: an `<se:FeatureTypeName>` inside an `<sld:LayerFeatureConstraints>` and/or inside an `<se:FeatureTypeStyle>`,
- for a coverage, with SLD/SE 1.1: an `<se:CoverageName>` inside an `<sld:LayerFeatureConstraints>` and/or inside an `<se:CoverageStyle>`,
- for SLD 1.0: a `<FeatureTypeName>` inside an `<LayerFeatureConstraints>` and/or inside a `<FeatureTypeStyle>`,
- or for compatibility with styles defined using this alternative approach: a `<Name>` element of the `<NamedLayer>` or `<UserLayer>`.

In the case of styles not explicitly referencing a feature type or coverage name, in the context of OGC APIs, the name of the layer will need to match the feature types
if declared in the data or the collections, or if not provided, the collection ID (see <<req_core_style-feature-type>>).
^|C |The more specific inner identifier element SHALL take priority to match individual feature types or coverages, as the layer `<Name>` may simply refer to a broader
collection container or a particular symbolization grouping (e.g., casing or center line).
|===

[[rec_sld-se_style-names]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/sld-se/style-names*
^|A |There SHOULD be a single `<UserStyle>` per layer, and they SHOULD all have the same `<Name>` value.
^|B |If a `UserStyle` has a `<Name>`, that name SHOULD correspond to the style id. The name is not relevant for the processing of the style, but may be assigned as the style id when
posting a new style.
^|C |For a stylesheet intended to style data available from an OGC API collection, the `UserStyle` SHOULD contain a feature type or coverage name identifier
(`<se:FeatureTypeName>` or `<se:CoverageName>` for SLD/SE 1.1, `<FeatureTypeName>` for SLD 1.0), either inside the `<LayerFeatureConstraints>` / `<sld:LayerFeatureConstraints>`,
or inside the `<FeatureTypeStyle>` / `<se:FeatureTypeStyle>` / `<se:CoverageStyle>`, set to the specific `featureType` name listed in the collection description,
or set to the `{collectionId}` if the collection contains a single feature type and no explicit feature types are listed.
|===

If there are multiple `UserStyle` elements in a layer, clients would select the style with a `<Name>` that matches the style id, if there is one.
Otherwise they can pick any of the styles.

[[rc_mapbox-styles]]
=== Requirements Class "Mapbox Style"

include::requirements/requirements_class_mapbox-style.adoc[]

[[req_mapbox-styles_media-type]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/mapbox-style/media-type*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL support the media type `application/vnd.mapbox.style+json`.
|===

[[req_mapbox-styles_content]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/mapbox-style/content*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL accept valid Mapbox Style documents (version 8) without errors.
|===

The list of operations in a server implementing all conformance classes of this draft specification is:

* POST `{baseResource}/styles`
* PUT `{baseResource}/styles/{styleId}`

[[rc_cscss-styles]]
=== Requirements Class "Cartographic Symbology CSS"

include::requirements/requirements_class_cscss-style.adoc[]

[[req_cscss-styles_media-type]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/cscss-style/media-type*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL support the media type `application/vnd.ogc.cartosym+css`.
|===

[[req_cscss-styles_content]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/cscss-style/content*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL accept valid CartoSym-CSS documents without errors.
|===

The list of operations in a server implementing all conformance classes of this draft specification is:

* POST `{baseResource}/styles`
* PUT `{baseResource}/styles/{styleId}`

[[rc_csjson-styles]]
=== Requirements Class "Cartographic Symbology JSON"

include::requirements/requirements_class_csjson-style.adoc[]

[[req_csjson-styles_media-type]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/csjson-style/media-type*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL support the media type `application/vnd.ogc.cartosym+json`.
|===

[[req_csjson-styles_content]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/csjson-style/content*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL accept valid CartoSym-JSON Style documents without errors.
|===

The list of operations in a server implementing all conformance classes of this draft specification is:

* POST `{baseResource}/styles`
* PUT `{baseResource}/styles/{styleId}`
