== Requirements Classes for Style Encodings

[[rc_sld-se]]
=== Requirements Class "OGC Styled Layer Descriptor / Symbology Encoding"

include::requirements/requirements_class_sld-se.adoc[]

[[req_sld-se_media-type]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sld-se/media-type*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL support the media type `application/vnd.ogc.sld+xml`.
^|B |The server SHALL accept either version 1.0 or 1.1 of SLD/SE (or both), specified with media type parameter `;version=1.0` or `;version=1.1`.
|===

[[req_sld-se_valid]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sld-se/valid*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL accept valid OGC SLD/SE documents without errors for the supported version(s).
|===

The list of operations in a server implementing all conformance classes of this draft specification is:

* POST `{baseResource}/styles`
* PUT `{baseResource}/styles/{styleId}`

[[sld-se_content]]
==== Expected content in an SLD/SE document

[[req_sld-se_root]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sld-se/root*
^|A |In accordance with the SLD/SE standard, the server SHALL accept SLD/SE stylesheets whose root element is a `StyledLayerDescriptor` element.
|===

The content of a stylesheet document will typically depend on the `{baseResource}`:

[[req_sld-se_content]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sld-se/content*
^|A |The document SHALL contain one or more `NamedLayer` or `UserLayer` elements, each with at least one `UserStyle`.
^|B |If `{baseResource}` is a Collection or Landing Page of an API that publishes a dataset (i.e., it includes a Collections resource at `/collections`), names corresponding to
collection ids SHALL be specified as the `FeatureTypeName` of a `FeatureTypeStyle` (for a feature collection) or as the `CoverageName` of a `CoverageStyle` (for a coverage),
and/or as the `Name` of a NamedLayer (for compatibility with this alternate approach to associate styles with collections).
|===

[[rec_sld-se_style-names]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/sld-se/style-names*
^|A |If a `UserStyle` has a name, it SHOULD correspond to the style id. The name is not relevant for the processing of the style, but may be assigned as the style id when
posting a new style.
^|B |The `UserStyle` SHOULD contain a `FeatureTypeStyle` element with a `FeatureTypeName`, or `CoverageStyle` element with a `CoverageName` corresponding to the collection id.
|===

In the case of a `NamedLayer` with both a `Name` and a `FeatureTypeStyle` with a `FeatureTypeName` (or a `CoverageStyle` with a `CoverageName`), clients should be prepared
to understand either of them, with the more specific `FeatureTypeName` or `CoverageName` taking priority (as in some cases the `Name` of the `NamedLayer` may refer to a
particular symbolization, e.g. casing or center line).

If there are multiple `UserStyle` elements in a layer, clients should use the style with a name that matches the style id, if there is one. Otherwise they should pick any of
the styles.

[[rc_mapbox-styles]]
=== Requirements Class "Mapbox Style"

include::requirements/requirements_class_mapbox-style.adoc[]

[[req_mapbox-styles_media-type]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/mapbox-style/media-type*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL support the media type `application/vnd.mapbox.style+json`.
|===

[[req_mapbox-styles_content]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/mapbox-style/content*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL accept valid Mapbox Style documents (version 8) without errors.
|===

The list of operations in a server implementing all conformance classes of this draft specification is:

* POST `{baseResource}/styles`
* PUT `{baseResource}/styles/{styleId}`

[[rc_cscss-styles]]
=== Requirements Class "Cartographic Symbology CSS"

include::requirements/requirements_class_cscss-style.adoc[]

[[req_cscss-styles_media-type]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/cscss-style/media-type*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL support the media type `application/vnd.ogc.cartosym+css`.
|===

[[req_cscss-styles_content]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/cscss-style/content*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL accept valid CartoSym-CSS documents without errors.
|===

The list of operations in a server implementing all conformance classes of this draft specification is:

* POST `{baseResource}/styles`
* PUT `{baseResource}/styles/{styleId}`

[[rc_csjson-styles]]
=== Requirements Class "Cartographic Symbology JSON"

include::requirements/requirements_class_csjson-style.adoc[]

[[req_csjson-styles_media-type]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/csjson-style/media-type*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL support the media type `application/vnd.ogc.cartosym+json`.
|===

[[req_csjson-styles_content]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/csjson-style/content*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL accept valid CartoSym-JSON Style documents without errors.
|===

The list of operations in a server implementing all conformance classes of this draft specification is:

* POST `{baseResource}/styles`
* PUT `{baseResource}/styles/{styleId}`
