name: Monthly SWG Report
on:
  schedule:
    - cron: "0 0 1 * *"
jobs:
  create_commit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create Monthly SWG Report
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Monthly SWG Report",
            "body": "Please discuss progress at the next SWG meeting and post a summary of the outcomes of the discussion in this GitHub Issue.\nTopics for the report include: status, progress in the last month, plans for next month, and risks.\n\nThis issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**.\nThe commit hash was: _${{ github.sha }}_."
            }' \
          --fail
